---
- name: Enable features on Spine
  hosts: spine
  connection: local
  gather_facts: no
  strategy: free
  
  roles:
    - common
    - spine
  
  vars:
    playbook_name: "Enable features on Spine"

  tasks:
    - name: Create checkpoint
      nxos_rollback:
        checkpoint_file: checkpoint.cfg
        provider: "{{ nxapi }}"
      tags:
        - create_checkpoint
    - block:
        - name: Ensure NETCONF is enabled
          nxos_feature:
            feature: netconf
            state: enabled
            provider: "{{ nxapi }}"
          tags:
            - enable_feature_netconf
        - name: Ensure OSPF is enabled
          nxos_feature:
            feature: ospf
            state: enabled
            provider: "{{ nxapi }}"
          tags:
            - enable_feature_ospf
        - name: Ensure BGP is enabled
          nxos_feature:
            feature: bgp
            state: enabled
            provider: "{{ nxapi }}"
          tags:
            - enable_feature_bgp
        - name: Ensure PIM is enabled
          nxos_feature:
            feature: pim
            state: enabled
            provider: "{{ nxapi }}"
          tags:
            - enable_feature_pim
        - name: Ensure scp-server is enabled
          nxos_feature:
            feature: scp-server
            state: enabled
            provider: "{{ nxapi }}"
          tags:
            - enable_feature_scp-server
        - name: Ensure NGOAM  is enabled
          nxos_feature:
            feature: ngoam
            state: enabled
            provider: "{{ nxapi }}"
          tags:
            - enable_feature_ngoam
      rescue:
        - set_fact:
            trigger_msg: True
            send_msg: "{{ playbook_name }} -  error configure on {{ inventory_hostname }}"
          changed_when: True
          notify: notify using spark
        - name: Rollback to checkpoint
          nxos_rollback:
            rollback_to: checkpoint.cfg
            provider: "{{ nxapi }}"
...
