---
- name: Generate VTEP Anycast Subnets
  hosts: [leaf,bleaf]
  connection: local
  gather_facts: no
  vars:
    generate_vtep_anycast_subnets:
      nbr_networks: 10
      network_size: 32
      network_pool: 10.154.154.0/24
    generate_vpc_link_subnets:
      nbr_networks: 10
      network_size: 30
      network_pool: 192.168.168.0/24
  roles:
    - generate_vtep_anycast_subnets
    - generate_vpc_link_subnets
- name: Generate VPC variables
  hosts: [leaf,bleaf]
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  vars:
    vpc:
      domain: 1000
      priority: 200 
      system_priority: 200
      vlan: 123
      po_id: 4096
      po_mode: active
      vrf: management
      peer_gw: true
      auto_recovery: true
      delay_restore: 150
  roles:
    - generate_vpc_variables
