services:
  - { vlanid: 100, service: l2l3vni, mtu: 9216, vrfname: VRFA, l3vnivlan: 10, gwipaddress: "192.168.123.254/24" }
l2service:
  interfaces:
    - { name: Eth1/1, mtu: 9216, mode: trunk, vlanid: 100, native: 1 }
bgp_address_families:
  - { vrf: VRFA, afi: ipv4, safi: unicast }
