underlay:
  ospf:
    routerid: Loopback0
    process: underlay
    area: 0
    cost: 1
  pim:
    interface: Loopback254
    address: 10.254.254.254
    mask: 30
    description: pim_rp_anycast
    grouplist: 233.0.0.0/24
  role: spine
  loopbacks:
    - interface: Loopback0
      ipaddress: 10.10.10.0
      mask: 32
      description: loopback_underlay
  interfaces:
    - interface: Eth2/2
      description: to_n9k-leaf-1_ethernet1/49
      ipaddress: 10.1.1.1
      mask: 30
      mtu: 9216
    - interface: Eth2/3
      description: to_n9k-leaf-2_ethernet1/49
      ipaddress: 10.1.1.5
      mask: 30
      mtu: 9216
    - interface: Eth2/11
      description: to_n9k-leaf-3_ethernet1/54
      ipaddress: 10.1.1.9
      mask: 30
      mtu: 9216
    - interface: Eth2/12
      description: to_n9k-leaf-4_ethernet1/54
      ipaddress: 10.1.1.13
      mask: 30
      mtu: 9216
    - interface: Eth2/1
      description: to_n9k-bleaf-1_ethernet1/49
      ipaddress: 10.1.1.17
      mask: 30
      mtu: 9216
